#!/bin/bash
set -e

version=$(grep -Po '(?<="version": ")\S*(?=")' package.json)
tagName="v$version"

if [ $(git tag -l "$tagName") ]; then
    echo "Tag \"$tagName\" already exists !!"
    exit 1
fi

echo "Creating tag \"$tagName\" ..."
git tag -m "Version $version" $tagName
echo "Tag \"$tagName\" created !!"

echo "Pushing tag to \"origin\" ..."
git push origin $tagName
echo "Tag \"$tagName\" pushed successfully !!"